export type Category =
  | "Utilities"
  | "Housing"
  | "Food"
  | "Transportation"
  | "Subscriptions"
  | "Healthcare"
  | "Insurance"
  | "Loans"
  | "Entertainment"
  | "Shopping"
  | "Services"
  | "Education"
  | "Charity"
  | "Pets"
  | "Uncategorized";
