import type { Category } from "@/components/category-selector";

// Keyword mappings for category suggestions
const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  Utilities: [
    "electric",
    "electricity",
    "power",
    "energy",
    "utility",
    "utilities",
    "water",
    "sewer",
    "gas",
    "natural gas",
    "internet",
    "wifi",
    "broadband",
    "phone",
    "telephone",
    "mobile",
    "cellular",
    "cable",
    "tv",
    "television",
    "trash",
    "garbage",
    "waste",
    "recycling",
    "sanitation",
  ],
  Housing: [
    "rent",
    "rental",
    "mortgage",
    "loan",
    "home loan",
    "hoa",
    "homeowners",
    "property tax",
    "property taxes",
    "home insurance",
    "homeowner insurance",
    "property insurance",
    "landlord",
    "apartment",
    "condo",
    "housing",
  ],
  Food: [
    "grocery",
    "groceries",
    "supermarket",
    "food",
    "restaurant",
    "dining",
    "delivery",
    "doordash",
    "ubereats",
    "grubhub",
    "coffee",
    "starbucks",
    "cafe",
    "bakery",
    "pizza",
    "fast food",
    "takeout",
  ],
  Transportation: [
    "car",
    "auto",
    "vehicle",
    "automobile",
    "car payment",
    "auto loan",
    "car insurance",
    "auto insurance",
    "gas",
    "fuel",
    "petrol",
    "gasoline",
    "parking",
    "transit",
    "metro",
    "subway",
    "bus",
    "train",
    "uber",
    "lyft",
    "rideshare",
    "taxi",
    "transportation",
  ],
  Subscriptions: [
    "netflix",
    "spotify",
    "apple",
    "music",
    "streaming",
    "subscription",
    "prime",
    "amazon prime",
    "hulu",
    "disney",
    "disney+",
    "hbo",
    "max",
    "paramount",
    "peacock",
    "youtube",
    "premium",
    "software",
    "saas",
    "membership",
    "gym",
    "fitness",
    "club",
  ],
  Healthcare: [
    "health",
    "healthcare",
    "medical",
    "doctor",
    "physician",
    "hospital",
    "clinic",
    "pharmacy",
    "drug",
    "prescription",
    "dental",
    "dentist",
    "vision",
    "eye",
    "optometrist",
    "insurance",
    "health insurance",
    "medical insurance",
  ],
  Insurance: [
    "life insurance",
    "disability insurance",
    "pet insurance",
    "insurance",
  ],
  Loans: [
    "student loan",
    "student loans",
    "personal loan",
    "credit card",
    "loan payment",
    "debt",
    "financing",
  ],
  Entertainment: [
    "movie",
    "movies",
    "cinema",
    "theater",
    "concert",
    "ticket",
    "tickets",
    "game",
    "games",
    "gaming",
    "hobby",
    "hobbies",
    "recreation",
    "sports",
    "entertainment",
  ],
  Shopping: [
    "retail",
    "store",
    "shop",
    "shopping",
    "amazon",
    "online",
    "purchase",
    "clothing",
    "clothes",
    "apparel",
    "household",
    "items",
    "merchandise",
  ],
  Services: [
    "legal",
    "lawyer",
    "attorney",
    "accounting",
    "accountant",
    "consulting",
    "consultant",
    "repair",
    "maintenance",
    "service",
    "services",
    "plumber",
    "electrician",
    "contractor",
  ],
  Education: [
    "tuition",
    "school",
    "university",
    "college",
    "education",
    "course",
    "courses",
    "training",
    "book",
    "books",
    "textbook",
    "learning",
  ],
  Charity: [
    "donation",
    "donations",
    "charity",
    "charitable",
    "giving",
    "nonprofit",
    "foundation",
    "fundraiser",
  ],
  Pets: [
    "pet",
    "pets",
    "dog",
    "cat",
    "veterinary",
    "vet",
    "animal",
    "pet food",
    "pet supplies",
    "pet store",
  ],
  Uncategorized: [],
};

/**
 * Suggests a category based on provider name using keyword matching
 */
export function suggestCategory(providerName: string): Category {
  if (!providerName || !providerName.trim()) {
    return "Uncategorized";
  }

  const normalizedProvider = providerName.toLowerCase().trim();

  // Count matches for each category
  const categoryScores: Record<Category, number> = {
    Utilities: 0,
    Housing: 0,
    Food: 0,
    Transportation: 0,
    Subscriptions: 0,
    Healthcare: 0,
    Insurance: 0,
    Loans: 0,
    Entertainment: 0,
    Shopping: 0,
    Services: 0,
    Education: 0,
    Charity: 0,
    Pets: 0,
    Uncategorized: 0,
  };

  // Score each category based on keyword matches
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    for (const keyword of keywords) {
      if (normalizedProvider.includes(keyword)) {
        categoryScores[category as Category]++;
      }
    }
  }

  // Find category with highest score
  let maxScore = 0;
  let suggestedCategory: Category = "Uncategorized";

  for (const [category, score] of Object.entries(categoryScores)) {
    if (score > maxScore) {
      maxScore = score;
      suggestedCategory = category as Category;
    }
  }

  // Only return suggestion if we have a confident match (score > 0)
  return maxScore > 0 ? suggestedCategory : "Uncategorized";
}
